/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CanCuRouteImport } from './routes/can-cu'
import { Route as LichSuRouteImport } from './routes/lich-su'
import { Route as XuHuongRouteImport } from './routes/xu-huong'
import { Route as PhienIdRouteImport } from './routes/phien.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanCuRoute = CanCuRouteImport.update({
  id: '/can-cu',
  path: '/can-cu',
  getParentRoute: () => rootRouteImport,
} as any)
const LichSuRoute = LichSuRouteImport.update({
  id: '/lich-su',
  path: '/lich-su',
  getParentRoute: () => rootRouteImport,
} as any)
const XuHuongRoute = XuHuongRouteImport.update({
  id: '/xu-huong',
  path: '/xu-huong',
  getParentRoute: () => rootRouteImport,
} as any)
const PhienIdRoute = PhienIdRouteImport.update({
  id: '/phien/$id',
  path: '/phien/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/can-cu': typeof CanCuRoute
  '/lich-su': typeof LichSuRoute
  '/xu-huong': typeof XuHuongRoute
  '/phien/$id': typeof PhienIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/can-cu': typeof CanCuRoute
  '/lich-su': typeof LichSuRoute
  '/xu-huong': typeof XuHuongRoute
  '/phien/$id': typeof PhienIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/can-cu': typeof CanCuRoute
  '/lich-su': typeof LichSuRoute
  '/xu-huong': typeof XuHuongRoute
  '/phien/$id': typeof PhienIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/can-cu' | '/lich-su' | '/xu-huong' | '/phien/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/can-cu' | '/lich-su' | '/xu-huong' | '/phien/$id'
  id: '__root__' | '/' | '/can-cu' | '/lich-su' | '/xu-huong' | '/phien/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanCuRoute: typeof CanCuRoute
  LichSuRoute: typeof LichSuRoute
  XuHuongRoute: typeof XuHuongRoute
  PhienIdRoute: typeof PhienIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/can-cu': {
      id: '/can-cu'
      path: '/can-cu'
      fullPath: '/can-cu'
      preLoaderRoute: typeof CanCuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lich-su': {
      id: '/lich-su'
      path: '/lich-su'
      fullPath: '/lich-su'
      preLoaderRoute: typeof LichSuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xu-huong': {
      id: '/xu-huong'
      path: '/xu-huong'
      fullPath: '/xu-huong'
      preLoaderRoute: typeof XuHuongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phien/$id': {
      id: '/phien/$id'
      path: '/phien/$id'
      fullPath: '/phien/$id'
      preLoaderRoute: typeof PhienIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanCuRoute: CanCuRoute,
  LichSuRoute: LichSuRoute,
  XuHuongRoute: XuHuongRoute,
  PhienIdRoute: PhienIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
